# Generated by Django 6.0.7 on 2026-07-30 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('refrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs_app.topic')),
            ],
            options={
                'verbose_name_plural': 'Entries',
            },
        ),
    ]
